### ISSUE TITLE
Doesn't work - polygon contains bug?

### ISSUE THREAD

**Issue by aaronaverill** [webmasterar/TimezoneMapperPHP#1]
I tested this with a location in Finland:

68.4, 27.4

I was surprised to find the class reports this as being in Russia timezone.

Debugging revealed that the code believes this point intersects with $poly[1675]. It does not.

Further investigation seems to indicate that the TzPolygon::contains() method doesn't work at all.

I tried to read the code but couldn't recognize the algorithm as being one of the standard polygon point intersection. I suggest it be rewritten to use an existing algorithm. Or one that works.

Unfortunately this means many many points will be reported wrong.

**Comment by webmasterar** [comment]
Thank you for reporting this issue! I just found the bug and fixed it.
