### ISSUE TITLE
Wrong timezone?

### ISSUE THREAD

**Issue by ofiser** [webmasterar/TimezoneMapperPHP#2]
Thanks for writing this utility, but somewhere there must be a problem.
Lat 51.2419425 Long 4.4737682 reports being London/Europe, but it should be Brussels (near to Antwerp).

Thanks for updating or signaling me how to correct.

Chris

**Comment by webmasterar** [comment]
Hello Ofiser.

I tried running this:
`<?php include 'TimezoneMapper.php'; echo TimezoneMapper::latLngToTimezoneString(51.2419425, 4.4737682); ?>`

and it output Europe/Brussels.

Make sure you have downloaded the latest version of the script and try again.

**Comment by ofiser** [comment]
Hello,

I just downloaded Timezonemapper yesterday (11/03) from github, thus using the last version?

Kind regards,
Chris

Op 11 maart 2018 23:25:31 +01:00, schreef A Retha <notifications@github.com>:

**Comment by webmasterar** [comment]
I did a fresh clone of the project from github just now and tried my PHP code again and it still outputs Europe/Brussels. So whatever the problem is, it's not TimezoneMapper.
